cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'                       # grep
brew 'asdf'                      # One Version Manager To Rule Them All
brew 'bash'
brew 'bat'                       # cat
brew 'coreutils'                 # https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities
brew 'curl'
brew 'diffutils'
brew 'fd'                        # Simple, fast, and user-friendly alternative to find
brew 'findutils'                 # classic GNU find
brew 'gawk'                      # GNU awk
brew 'git'                       # Should be installed when homebrew is installed, but this just makes it official
brew 'git-delta'                 # Syntax-highlighting pager for git and diff output
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnu-which'
brew 'go'
brew 'gpg'
brew 'gpg2'
brew 'graphviz'                  # Create graphs and diagrams using a text-based DSL
brew 'grep'                      # GNU grep
brew 'gzip'
brew 'hub'                       # CLI for GitHub
brew 'imagemagick'
brew 'jq'                        # json query
brew 'lastpass-cli'              # Lastpass on the command line!
brew 'kubernetes-cli'
brew 'k9s'
brew 'libgit2'
brew 'mas'                       # Mac App Store command-line interface
brew 'moreutils'                 # Yet more useful utility commands
brew 'node'                      # Node.JS
brew 'openssl'
brew 'pinentry-mac'              # Useful password entry -- needed to store gpg key passphrases in the Mac Keychain and such
brew 'poetry'                    # Python package management tool
brew 'readline'                  # enables command-line editing with vi/emacs keybindings
brew 'renameutils'               # provides icp and imv
brew 'shellcheck'
brew 'tree'                      # show directory structures on the commandline
brew 'watch'                     # watch command that lets you run a command periodically, showing output in fullscreen
brew 'wget'
brew 'yq'                        # like jq, for yaml
brew 'zsh-syntax-highlighting'
brew 'zsh'

cask 'docker'
cask 'firefox'
cask 'font-jetbrains-mono-nerd-font'
cask 'google-chrome'
cask 'insomnia'
cask 'iterm2'
cask 'lastpass'
cask 'slack'
cask 'spectacle'
